"""added uploaded by.

Revision ID: 2914e7380162
Revises: 3566941c9cc7
Create Date: 2022-06-20 16:32:50.663726

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '2914e7380162'
down_revision = '3566941c9cc7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('uploaded_by', sa.String()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'uploaded_by')
    # ### end Alembic commands ###
