"""Initial scheme.

Revision ID: c16a3043d0c4
Revises: 
Create Date: 2022-04-20 17:39:52.504913

"""
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op
from server import db

# revision identifiers, used by Alembic.
revision = 'c16a3043d0c4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('video_category', sa.String(length=510), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('video_category')
    )
    op.create_table('videos',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('uploaded_at', db.UtcTimestamp(timezone=True), server_default=sa.text('current_timestamp'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('videos')
    op.drop_table('categories')
    # ### end Alembic commands ###
